### PR TITLE
Dockerfile and docker-compose added

### PR DESCRIPTION
**Pull request by foxpowa**
Hard work to add Dockerfile and docker-compose yaml file to ensure we are able to run these amazing notebooks.

I've modified conda env config file a little bit, feel free to update it ;)
Dockerfile can be simplified, since I used a Dockerfile from jupyter  docker stack to create mine.

I've executed all cells from PyTorch without error. However it may be errors or missing packages.

### CODE REVIEW

**Comment by Spandan-Madan** [comment]
@AnshulBasia Can you take a look and merge if all looks good? :)

**Comment by AnshulBasia** [comment]
@foxpowa  Thanks a lot. I was wondering if you could answer some questions:
1.) Is this docker file explicit for ubuntu or will it work for any unix based OS ?
2.) Could you also make another section in readme on how to use this docker file instead of a bunch of instructions already mentioned there ?

**Comment by Spandan-Madan** [comment]
I think if it's docker it should work on any system supported by Docker, so that should be ok. Right @foxpowa ?

Also yeah, the edits in the readme with Docker support would be a great addition!

**Comment by foxpowa** [comment]
Hi folks,
1) It will work on any system that runs Docker, I've tested it on my mac and my ubuntu 16.04 linux computer.
2) Sure, I'll add some info to run it via docker-compose (basically, docker run command will be nicely stored in a yaml config file).

**Pull request merged**
